# Generated by Django 3.1.5 on 2021-01-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_auto_20210127_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('arquivo', models.FileField(upload_to='PDFfiles', verbose_name='Arquivo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
            },
        ),
    ]
