# Generated by Django 3.1.5 on 2021-02-24 18:34

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_arquivopdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('imagem', stdimage.models.StdImageField(upload_to='img_historico', verbose_name='Imagem')),
                ('subtitulo01', models.CharField(max_length=100, verbose_name='Subtítulo01')),
                ('descricao01', models.TextField(max_length=200, verbose_name='Subtítulo01 Descrição')),
                ('subtitulo02', models.CharField(max_length=100, verbose_name='Subtítulo02')),
                ('descricao02', models.TextField(max_length=200, verbose_name='Subtítulo02 Descrição')),
                ('contador01', models.CharField(max_length=50, verbose_name='contador01')),
                ('valor01', models.TextField(max_length=6, verbose_name='valor contador01')),
                ('contador02', models.CharField(max_length=50, verbose_name='contador02')),
                ('valor02', models.TextField(max_length=6, verbose_name='valor contador02')),
                ('contador03', models.CharField(max_length=50, verbose_name='contador03')),
                ('valor03', models.TextField(max_length=6, verbose_name='valor contador03')),
                ('subtitulo03', models.CharField(max_length=100, verbose_name='Subtítulo03')),
                ('descricao03', models.TextField(max_length=200, verbose_name='Subtítulo03 Descrição')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Noticias',
            },
        ),
        migrations.AddField(
            model_name='arquivopdf',
            name='descricao',
            field=models.TextField(default=1, max_length=200, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arquivopdf',
            name='titulo',
            field=models.CharField(default=1, max_length=100, verbose_name='Título'),
            preserve_default=False,
        ),
    ]
