# Generated by Django 3.1.5 on 2021-02-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0005_auto_20210224_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historico',
            options={'verbose_name': 'Histórico'},
        ),
        migrations.AlterField(
            model_name='historico',
            name='valor01',
            field=models.CharField(max_length=6, verbose_name='valor contador01'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='valor02',
            field=models.CharField(max_length=6, verbose_name='valor contador02'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='valor03',
            field=models.CharField(max_length=6, verbose_name='valor contador03'),
        ),
    ]
