# Generated by Django 3.1.5 on 2021-02-25 00:04

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0006_auto_20210224_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='descricao03',
            field=models.TextField(blank=True, max_length=200, verbose_name='Subtítulo03 Descrição'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, upload_to='img_historico', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='subtitulo03',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subtítulo03'),
        ),
    ]
