# Generated by Django 3.1.5 on 2021-02-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0007_auto_20210224_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='descricao01',
            field=models.TextField(max_length=800, verbose_name='Subtítulo01 Descrição'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='descricao02',
            field=models.TextField(max_length=800, verbose_name='Subtítulo02 Descrição'),
        ),
        migrations.AlterField(
            model_name='historico',
            name='descricao03',
            field=models.TextField(blank=True, max_length=800, verbose_name='Subtítulo03 Descrição'),
        ),
    ]
