# Generated by Django 3.1.5 on 2021-02-25 19:10

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0008_auto_20210225_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('subtitulo01', models.CharField(max_length=100, verbose_name='Subtítulo01')),
                ('descricao01', models.TextField(max_length=800, verbose_name='Subtítulo01 Descrição')),
                ('imagem01', stdimage.models.StdImageField(blank=True, upload_to='img_historico', verbose_name='Imagem')),
                ('subtitulo02', models.CharField(max_length=100, verbose_name='Subtítulo01')),
                ('descricao02', models.TextField(max_length=800, verbose_name='Subtítulo01 Descrição')),
                ('imagem02', stdimage.models.StdImageField(blank=True, upload_to='img_historico', verbose_name='Imagem')),
                ('subtitulo03', models.CharField(max_length=100, verbose_name='Subtítulo01')),
                ('descricao03', models.TextField(max_length=800, verbose_name='Subtítulo01 Descrição')),
                ('imagem03', stdimage.models.StdImageField(blank=True, upload_to='img_historico', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Princípio',
            },
        ),
    ]
