# Generated by Django 3.1.5 on 2021-02-26 00:20

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0009_principios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historico',
            options={'verbose_name': 'Histórico', 'verbose_name_plural': 'Histórico'},
        ),
        migrations.AlterModelOptions(
            name='principios',
            options={'verbose_name': 'Princípio', 'verbose_name_plural': 'Princípio'},
        ),
        migrations.AlterField(
            model_name='arquivopdf',
            name='descricao',
            field=models.TextField(max_length=450, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='principios',
            name='descricao02',
            field=models.TextField(max_length=800, verbose_name='Subtítulo02 Descrição'),
        ),
        migrations.AlterField(
            model_name='principios',
            name='descricao03',
            field=models.TextField(max_length=800, verbose_name='Subtítulo03 Descrição'),
        ),
        migrations.AlterField(
            model_name='principios',
            name='imagem01',
            field=stdimage.models.StdImageField(blank=True, upload_to='img_principio', verbose_name='Imagem01'),
        ),
        migrations.AlterField(
            model_name='principios',
            name='imagem02',
            field=stdimage.models.StdImageField(blank=True, upload_to='img_principio', verbose_name='Imagem02'),
        ),
        migrations.AlterField(
            model_name='principios',
            name='imagem03',
            field=stdimage.models.StdImageField(blank=True, upload_to='img_principio', verbose_name='Imagem03'),
        ),
        migrations.AlterField(
            model_name='principios',
            name='subtitulo02',
            field=models.CharField(max_length=100, verbose_name='Subtítulo02'),
        ),
        migrations.AlterField(
            model_name='principios',
            name='subtitulo03',
            field=models.CharField(max_length=100, verbose_name='Subtítulo03'),
        ),
        migrations.CreateModel(
            name='CodigoEtica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('arquivo', models.FileField(upload_to='PDFfiles', verbose_name='Arquivo')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Código de Ética',
                'verbose_name_plural': 'Código de Ética',
            },
        ),
    ]
