# Generated by Django 3.1.5 on 2021-02-28 01:19

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0010_auto_20210225_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeComite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('atuacao', models.CharField(max_length=100, verbose_name='Atuação')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('imagem', stdimage.models.StdImageField(blank=True, upload_to='img_principio', verbose_name='Imagem')),
                ('face', models.CharField(max_length=100, verbose_name='Facebook')),
                ('gmais', models.CharField(max_length=100, verbose_name='Google+')),
                ('twitter', models.CharField(max_length=100, verbose_name='Twitter')),
                ('instagram', models.CharField(max_length=100, verbose_name='Instagram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipeDeliberativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('atuacao', models.CharField(max_length=100, verbose_name='Atuação')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('imagem', stdimage.models.StdImageField(blank=True, upload_to='img_principio', verbose_name='Imagem')),
                ('face', models.CharField(max_length=100, verbose_name='Facebook')),
                ('gmais', models.CharField(max_length=100, verbose_name='Google+')),
                ('twitter', models.CharField(max_length=100, verbose_name='Twitter')),
                ('instagram', models.CharField(max_length=100, verbose_name='Instagram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipeFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('atuacao', models.CharField(max_length=100, verbose_name='Atuação')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('imagem', stdimage.models.StdImageField(blank=True, upload_to='img_principio', verbose_name='Imagem')),
                ('face', models.CharField(max_length=100, verbose_name='Facebook')),
                ('gmais', models.CharField(max_length=100, verbose_name='Google+')),
                ('twitter', models.CharField(max_length=100, verbose_name='Twitter')),
                ('instagram', models.CharField(max_length=100, verbose_name='Instagram')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipeInstituto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('atuacao', models.CharField(max_length=100, verbose_name='Atuação')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('imagem', stdimage.models.StdImageField(blank=True, upload_to='img_principio', verbose_name='Imagem')),
                ('face', models.CharField(max_length=100, verbose_name='Facebook')),
                ('gmais', models.CharField(max_length=100, verbose_name='Google+')),
                ('twitter', models.CharField(max_length=100, verbose_name='Twitter')),
                ('instagram', models.CharField(max_length=100, verbose_name='Instagram')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
