# Generated by Django 3.1.5 on 2021-02-28 01:42

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0011_equipecomite_equipedeliberativo_equipefiscal_equipeinstituto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipecomite',
            options={'verbose_name': 'Equipe Comitê de Investimento', 'verbose_name_plural': 'Equipe Comitê de Investimento'},
        ),
        migrations.AlterModelOptions(
            name='equipedeliberativo',
            options={'verbose_name': 'Equipe Conselho Deliberativo', 'verbose_name_plural': 'Equipe Conselho Deliberativo'},
        ),
        migrations.AlterModelOptions(
            name='equipefiscal',
            options={'verbose_name': 'Equipe Conselho Fiscal', 'verbose_name_plural': 'Equipe Conselho Fiscal'},
        ),
        migrations.AlterModelOptions(
            name='equipeinstituto',
            options={'verbose_name': 'Equipe Instituto', 'verbose_name_plural': 'Equipe Instituto'},
        ),
        migrations.AlterField(
            model_name='equipecomite',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, upload_to='EquipeComite', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='equipedeliberativo',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, upload_to='EquipeDeliberativo', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='equipefiscal',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, upload_to='EquipeFiscal', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='equipeinstituto',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, upload_to='EquipeInstituto', verbose_name='Imagem'),
        ),
    ]
