# Generated by Django 3.1.5 on 2021-02-28 03:12

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0012_auto_20210227_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(max_length=800, verbose_name='Descrição')),
                ('imagem', stdimage.models.StdImageField(blank=True, upload_to='Concursos', verbose_name='Imagem')),
                ('arquivo', models.FileField(upload_to='PDFfiles', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Concurso',
                'verbose_name_plural': 'Concursos',
            },
        ),
    ]
