# Generated by Django 3.1.5 on 2021-03-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0014_educacaoprevidenciaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoAcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(max_length=800, verbose_name='Descrição')),
                ('arquivo', models.FileField(upload_to='PDFfiles', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Plano de Ação',
                'verbose_name_plural': 'Plano de Ação',
            },
        ),
    ]
