# Generated by Django 3.1.5 on 2021-03-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0016_gestaocontroleinterno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('questaoTexto', models.CharField(max_length=200)),
                ('escolhaTexto', models.CharField(max_length=200)),
                ('votos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Questionário',
                'verbose_name_plural': 'Questionário',
            },
        ),
    ]
