# Generated by Django 3.1.5 on 2021-03-05 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0018_auto_20210304_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('pergunta', models.CharField(max_length=200, verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('ruim', models.IntegerField(verbose_name='Ruim')),
                ('regular', models.IntegerField(verbose_name='Regular')),
                ('bom', models.IntegerField(verbose_name='Bom')),
                ('otimo', models.IntegerField(verbose_name='Ótimo')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.questionario', verbose_name='Pergunta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
