# Generated by Django 3.1.5 on 2021-03-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0019_auto_20210305_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='bom',
            field=models.IntegerField(default=0, verbose_name='Bom'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='otimo',
            field=models.IntegerField(default=0, verbose_name='Ótimo'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='regular',
            field=models.IntegerField(default=0, verbose_name='Regular'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='ruim',
            field=models.IntegerField(default=0, verbose_name='Ruim'),
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
    ]
