# Generated by Django 3.1.5 on 2021-03-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0021_auto_20210305_2105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionario',
            options={'verbose_name': 'Questionario', 'verbose_name_plural': 'Questionários'},
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='criados',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='modificado',
        ),
    ]
