# Generated by Django 3.1.5 on 2021-03-06 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0022_auto_20210306_0253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionario',
            options={},
        ),
    ]
