# Generated by Django 3.1.5 on 2021-03-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0024_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_text2',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text3',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text4',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='votes2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='votes3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='votes4',
            field=models.IntegerField(default=0),
        ),
    ]
